language: swift
osx_image: xcode10.2
notifications:
  email: false
before_install:
  - gem install fastlane -no-ri-no-rdoc --no-document
jobs:
  include:
    - stage: Test
      name: XCTest
      script: fastlane scan -s HelloWorldTests
    - stage: Test
      name: XCUITest
      script: fastlane scan -s HelloWorldUITests
